[target.x86_64-unknown-linux-musl]
image = "brainstorm/cross-x86_64-unknown-linux-musl:libcurl-openssl"
[target.x86_64-unknown-linux-gnu]
image = "brainstorm/cross-x86_64-unknown-linux-gnu-0.1.16:libcurl-openssl"
