[build.env]
passthrough = [
    "RUST_DEBUG",
    "RUST_BACKTRACE",
    "CFLAGS"
]

[target.x86_64-unknown-linux-musl]
image = "rustembedded/cross:x86_64-unknown-linux-musl"
[target.x86_64-unknown-linux-gnu]
image = "rustembedded/cross:x86_64-unknown-linux-gnu"
